version: '3.3'

services:
  # phpapache:
  #   build: ./php
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   depends_on:
  #     - mysql
  #   volumes:
  #     - ./www:/var/www/html
  mysql:
    container_name: mysql
    build: ./database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
  phpapi:
    container_name: phpapi
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306