version: '3.3'

services:
  mysql:
    container_name: mysql
    build: ./database
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    networks:
      laravel:
  phpmyadmin:
    container_name: sqladmin
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
    networks:
      laravel:
  phpapi:
    container_name: phpapi
    build: .
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    networks:
      laravel:
networks:
  laravel: